### PR TITLE
Ukrainian translate

### PR DESCRIPTION
**Pull request by unroman**

### CODE REVIEW

**Comment by magistermaks** [comment]
Thanks for contributing!

**Comment by magistermaks** [comment]
There was some new content added in RedBits 1.16.0
- some new translation keys
- two new guide book pages (and some minor changes to some older pages, i believe)  

would you be interested in updating your translation to reflect those changes?

**Comment by magistermaks** [comment]
@unroman There was some new content added in RedBits 1.16.0
- some new translation keys
- two new guide book pages (and some minor changes to some older pages, i believe)  

would you be interested in updating your translation to reflect those changes?

**Comment by unroman** [comment]
@magistermaks yeah sure

**Pull request merged**
